services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: pokeapi
    container_name: pokeapi
    ports:
      - "8000:8000"
    environment:
      - POKEAPI_BASE_URL=https://pokeapi.co/api/v2
